server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: pedido
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 4
        max-concurrency: 4
        prefetch: 4
