name: Continuous Integration With Github Actions

on:
  push:
    branches: 
     - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps: 
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build -x test --stacktrace --info

    - name: Docker Compose Build Application JAR
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
       docker tag venda-producer ${{ secrets.DOCKER_USERNAME }}/venda-producer:${{ github.run_id }}
       docker tag venda-producer ${{ secrets.DOCKER_USERNAME }}/venda-producer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/venda-producer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/venda-producer:latest
       
       docker tag venda-consumer ${{ secrets.DOCKER_USERNAME }}/venda-consumer:${{ github.run_id }}
       docker tag venda-consumer ${{ secrets.DOCKER_USERNAME }}/venda-consumer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/venda-consumer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/venda-consumer:latest
       
       docker tag pedido-producer ${{ secrets.DOCKER_USERNAME }}/pedido-producer:${{ github.run_id }}
       docker tag pedido-producer ${{ secrets.DOCKER_USERNAME }}/pedido-producer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/pedido-producer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/pedido-producer:latest
       
       docker tag pedido-consumer ${{ secrets.DOCKER_USERNAME }}/pedido-consumer:${{ github.run_id }}
       docker tag pedido-consumer ${{ secrets.DOCKER_USERNAME }}/pedido-consumer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/pedido-consumer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/pedido-consumer:latest
       
       docker tag transacao-producer ${{ secrets.DOCKER_USERNAME }}/transacao-producer:${{ github.run_id }}
       docker tag transacao-producer ${{ secrets.DOCKER_USERNAME }}/transacao-producer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/transacao-producer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/transacao-producer:latest
       
       docker tag transacao-consumer ${{ secrets.DOCKER_USERNAME }}/transacao-consumer:${{ github.run_id }}
       docker tag transacao-consumer ${{ secrets.DOCKER_USERNAME }}/transacao-consumer:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/transacao-consumer:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/transacao-consumer:latest
